name: GitOps CI/CD
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
env:
  REPO_NAME: ${{ github.repository }}
  CONTAINER_NAME: devops-journey
  REGISTRY: ghcr.io
  MANIFEST_REPO_URL: ${{ secrets.MANIFEST_REPO_URL }}
  MANIFEST_PATH: ${{ secrets.MANIFEST_PATH }}
 
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}"
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}:buildcache,mode=max

  
  update-manifest:
    runs-on: ubuntu-latest
    needs: ['build_and_push']
    steps:
      - name: Update manifest repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.MANIFEST_REPO_URL }}
          path: manifests
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: main  
 
      - name: Update deployment.yaml in manifest repository
        run: |
          cd manifests
          echo "${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}"
          new_image="${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}"
        
          sed -i "s|image: .*|image: $new_image|g" ${{ env.MANIFEST_PATH }}/deployment.yaml      
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add ${{ env.MANIFEST_PATH }}/deployment.yaml
          git diff --cached --exit-code || git commit -m "Update image tag to $new_image" && git push origin main